### ISSUE TITLE
is it available for swift?

### ISSUE THREAD

**Issue by akshay-cemtrexlabs** [MaximKomlev/RTSPAVPlayer#1]

**Comment by MaximKomlev** [comment]
yes, it can be used in swift as well. please note it is draft, it is still require tuning and work for production readiness.

**Comment by akshay-cemtrexlabs** [comment]
The library is working properly in objective c but when i create the instance of RTSPAVPlayer it is not showing the init instead it is taking the default init of avplayer thats the  issue in swift. thank you!

**Comment by MaximKomlev** [comment]
you can check now, i added swift example.

**Comment by akshay-cemtrexlabs** [comment]
I really appreciate your help, Thank You!
