### ISSUE TITLE
Getting this error when i run the project "'libavformat/avformat.h' file not found"

### ISSUE THREAD

**Issue by Mayankpalotra** [MaximKomlev/RTSPAVPlayer#2]
Hello @MaximKomlev, First of all thank you for your super library to help a-lot.
I am getting this error when i run this project.

'libavformat/avformat.h' file not found
<img width="1440" alt="Screenshot 2020-10-15 at 1 15 45 PM" src="https://user-images.githubusercontent.com/10432844/96094190-ad720900-0eea-11eb-9d77-bf9087235c67.png">

**Comment by MaximKomlev** [comment]
Hi @Mayankpalotra , i hope it is helpful, to have it be built, you need to compile ffmpeg. https://github.com/MaximKomlev/RTSPAVPlayer/tree/master/RTSPAVPlayer/thirdparty/ffmpeg/general

**Comment by Mayankpalotra** [comment]
Ok @MaximKomlev i'll try. Thanks

**Comment by bhadjajay23** [comment]
@MaximKomlev Getting same error.
 Is there any solution to resolved this error?
Please help.

**Comment by MaximKomlev** [comment]
@bhadjajay23 Please use https://github.com/MaximKomlev/RTSPAVPlayer/tree/master/RTSPAVPlayer/thirdparty/ffmpeg/general ffmpeg build script to build ffmpeg libraries, when it is done, please build app one more time.

**Comment by amitsanvedi-valere** [comment]
> Hi @Mayankpalotra , i hope it is helpful, to have it be built, you need to compile ffmpeg. https://github.com/MaximKomlev/RTSPAVPlayer/tree/master/RTSPAVPlayer/thirdparty/ffmpeg/general

Thanks @MaximKomlev my problem has been resolved!!!

**Comment by Mayankpalotra** [comment]
> Hi @Mayankpalotra , i hope it is helpful, to have it be built, you need to compile ffmpeg. https://github.com/MaximKomlev/RTSPAVPlayer/tree/master/RTSPAVPlayer/thirdparty/ffmpeg/general

Thanks @MaximKomlev My problem has been resolved from given link!!!

**Comment by AnhGio** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/16881482/199392649-ce447064-d82c-4c68-b048-9d8b6fb421e3.png">

@MaximKomlev I have run scrip but It's still error 'libavformat/avformat.h' file not found
